kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:v0.8
  - linuxkit/runc:v0.8
  - linuxkit/containerd:v0.8
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: rngd1
    image: linuxkit/rngd:v0.8
    command: ["rngd", "-1"]
services:
  - name: getty
    image: linuxkit/getty:v0.8
    binds.add:
      - /etc/profile.d/local.sh:/etc/profile.d/local.sh
    env:
     - INSECURE=true

files:
#  - path: /tail.sh
#    source: ./tail.sh
  - path: etc/profile.d/local.sh
    contents: |
      alias debug-image='ctr -n services.linuxkit tasks exec --tty --exec-id image image /bin/bash'
    mode: "0644"
