kernel:
  image: ghcr.io/netbootxyz/kernel:5.10.104-236e4584f434a1efde678bd276c9b533a5e872ba-amd64
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:14df799bb3b9e0eb0491da9fda7f32a108a2e2a5
  - linuxkit/runc:436357ce16dd663e24f595bcec26d5ae476c998e
  - linuxkit/containerd:eeb3aaf497c0b3f6c67f3a245d61ea5a568ca718
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:2a8ed08fea442909ba10f950d458191ed3647115
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: rngd1
    image: linuxkit/rngd:331294919ba6d953d261a2694019b659a98535a4
    command: ["rngd", "-1"]
services:
  - name: getty
    image: linuxkit/getty:06f34bce0facea79161566d67345c3ea49965437
    binds.add:
      - /etc/profile.d/local.sh:/etc/profile.d/local.sh
    env:
     - INSECURE=true
  - name: core
    image: ghcr.io/netbootxyz/core:latest
    capabilities:
      - all
    net: host
    pid: host
    binds:
      - /dev/console:/dev/console
      - /dev:/dev
      - /etc/resolv.conf:/etc/resolv.conf
      - /lib/modules:/lib/modules
  - name: core-tail
    image: alpine:3.17
    pid: host
    command: ["sh", "/tail.sh"]
    binds:
      - /var/log:/var/log
      - /tail.sh:/tail.sh
      - /dev/console:/dev/console
      - /dev/ttyS0:/dev/ttyS0
      - /dev/tty0:/dev/tty0
    devices:
      - path: "/dev/console"
        type: c
        major: 5
        minor: 1
        mode: "0666"
      - path: "/dev/tty0"
        type: c
        major: 4
        minor: 0
        mode: "0666"
      - path: "/dev/ttyS0"
        type: c
        major: 4
        minor: 64
        mode: "0666"
    capabilities:
      - CAP_SYS_BOOT

files:
  - path: /tail.sh
    source: ./scripts/tail.sh
  - path: etc/profile.d/local.sh
    contents: |
      alias debug-core='ctr -n services.linuxkit tasks exec --tty --exec-id core core /bin/bash'
      alias reload-core='ctr -n services.linuxkit tasks exec --tty --exec-id core core cd /opt/core; ansible-playbook -i localhost reload.yml'
    mode: "0644"
