name: Generate Images
on:
  push:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  build-kernel:
    runs-on: ubuntu-latest
    container:
      image: docker:28.0.1
      env:
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
    steps:
    - name: Build core kernel
      run: |
        apk add git make
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build core kernel
      run: |
        cd kernel
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        KERNEL_SHA=`git ls-tree --full-tree HEAD -- kernel | awk '{print $3}'`
        echo Current KERNEL_SHA is $KERNEL_SHA
        make kconfig
        make ORG=ghcr.io/netbootxyz build_5.10.x
        docker push ghcr.io/netbootxyz/kernel:5.10.104-$KERNEL_SHA-amd64

  build-os:
    needs: build-kernel
    runs-on: ubuntu-latest
    container:
      image: docker:28.0.1
      env:
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
        CURRENT_TAG: 0.0.1
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Build core image
      run: |
        apk add git wget docker curl make
        mkdir -p out
        wget https://github.com/linuxkit/linuxkit/releases/download/v1.5.0/linuxkit-linux-amd64
        chmod +x linuxkit-linux-amd64
        ./linuxkit-linux-amd64 build --format kernel+initrd --name core --dir out core.yml
    - name: Generate pre-release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          out/*
