name: Generate Images
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  build-kernel:
    runs-on: ubuntu-latest
    container:
      image: docker:20.10.21
      env:
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to the GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build core kernel
      run: |
        apk add git make
        cd kernel
        export KERNEL_SHA=`git ls-tree --full-tree HEAD -- kernel | awk '{print $3}'`
        make kconfig
        make ORG=ghcr.io/netbootxyz build_5.15.x
        docker push ghcr.io/netbootxyz/kernel:5.15.27-${KERNEL_SHA}-amd64

  build-os:
    needs: build-kernel
    runs-on: ubuntu-latest
    container:
      image: docker:20.10.21
      env:
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
        CURRENT_TAG: 0.0.1
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Build core image
      run: |
        apk add git wget docker curl make
        mkdir -p out
        wget https://github.com/linuxkit/linuxkit/releases/download/v1.0.1/linuxkit-linux-amd64
        chmod +x linuxkit-linux-amd64
        ./linuxkit-linux-amd64 build -format kernel+initrd -format iso-efi-initrd -format kernel+iso -name core -dir out core.yml
