name: Build Kernel
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    container:
    image: docker:20.10.21
    env:
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Build core image
      run: |
        apk add git make
        cd kernel
        KERNEL_SHA=`git ls-tree --full-tree HEAD -- kernel | awk '{print $3}'`
        make kconfig
